pipeline{
    agent any

    tools{
        jdk 'java-11'
        maven 'Maven'
    }

    stages{
        stage('Git-Checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/danush242211ay/devopspro1.git'
            }
        }
    }
}